steps:
  - task: Docker@2
    displayName: Docker build
    inputs:
      command: build
      repository: 'gb3-frontend'
      dockerfile: '**/Dockerfile'
      arguments: '--build-arg TARGET_ENVIRONMENT=production'
      tags: 'latest'
