steps:
  - task: SonarCloudPrepare@1
    displayName: 'Prepare Sonar Cloud WebClient'
    inputs:
      SonarCloud: 'EBP Sonar Cloud'
      organization: 'ebpgroup'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: '222262_GB3_frontend'
      cliProjectName: '222262_GB3_frontend'
      cliSources: 'src'
      extraProperties: |
        sonar.javascript.lcov.reportPaths=$(System.DefaultWorkingDirectory)/coverage/gb3-frontend/lcov.info

  - task: SonarCloudAnalyze@1
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
