steps:
  - task: SonarCloudPrepare@1
    displayName: 'Prepare Sonar Cloud WebClient'
    inputs:
      SonarCloud: 'EBP Sonar Cloud'
      organization: 'ebpgroup'
      scannerMode: 'CLI'
      configMode: 'file'
  - task: SonarCloudAnalyze@1
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
