steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm run test-ci
    displayName: 'npm install and test'
