trigger: none

variables:
  - template: 'templates/variables.yaml'

pool:
  vmImage: $(VM_IMAGE)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm run test
    displayName: 'npm install and test'
