trigger: none # only run in PRs which are handled by branch policies

variables:
  - template: 'templates/variables.yml'

pool:
  vmImage: $(VM_IMAGE)

steps:
  - template: 'templates/git-checkout-code.yml'
  - template: 'templates/sonar-cloud-analysis.yml'
