name: Ensure build and test quality for main and develop

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  node:
    if: github.ref == 'disabled'
    name: Node
    uses: ./.github/workflows/node-tests.yml

  docker:
    if: github.ref == 'disabled'
    name: Docker
    uses: ./.github/workflows/docker-dry-run.yml

  deploy-dev:
    name: Deploy dev environment
    if: github.ref == 'refs/heads/main' # todo: change
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies and build
        env:
          APP_RELEASE: 'EBP Dev Release'
        run: |
          npm ci
          npm run build-dev-ebp

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/browser
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



    # todo: sonar analysis
