name: Ensure build and test quality for main and develop

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  node:
    name: Node
    uses: ./.github/workflows/node-tests.yml

  docker:
    name: Docker
    uses: ./.github/workflows/docker-dry-run.yml

    # todo: sonar analysis
